### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by nilskp** [rkostrzewski/vscode-monitor-file#1]
No reloading.

**Comment by nilskp** [comment]
Nevermind, it does work, but there are sporadic cases of not.

**Comment by rkostrzewski** [comment]
Was it a delay of reloading (it might happen for various logging libraries which flush data from memory to disk to reduce I/O overhead) or was it completely not reloading even tough a file could be opened in a different editor? OS name & version will help in determining the issue. Thanks.

**Comment by nilskp** [comment]
I'm on Windows 10. 

I still see this, to varying degrees. I'm not sure how reloading is determined, but I wonder if it's related to reading timestamps, perhaps something with differences between linux and windows and/or related to precision, i.e. millis or seconds.

**Comment by nilskp** [comment]
So, I just saw this again. Last log line shown has timestamp `2017-07-25 13:39:01.133`, and then never updates again.
Invoking `F1` + `Monitor File` is necessary to refresh and shows the following log lines, the next immediate one having timestamp `2017-07-25 13:39:03.754`.
So, there's a 2+ second delay between those two lines, but that line (and all following) is never picked up.

**Comment by nilskp** [comment]
It's almost certainly some race condition, that seems to bring it into a state where it stops reacting.
I'm surprised if I'm the only one seeing this.

**Comment by nilskp** [comment]
Appears to be resolved when I switched to 64-bit version of VSC.
