### ISSUE TITLE
running the contributed command extension.monitorfile failed

### ISSUE THREAD

**Issue by xgdgsc** [rkostrzewski/vscode-monitor-file#2]
Whee  I run monitor file command, it shows and error message saying: `running the contributed command extension.monitorfile failed` . I' m on centos with vs code 1.12.2.

**Comment by xgdgsc** [comment]
Seems only happens with large files, such as a 30MB log file. Works fine with small files.

**Comment by rkostrzewski** [comment]
Hi, sorry for responding so late. For some weird reason I was not receiving notifications from this repository.

Unfortunately, I'm not planning to work on this extension anymore so I'm gonna close this issue. If you'd like to contribute feel free to fork the repository. Sorry 🙇
