### ISSUE TITLE
Scroll down after reload option

### ISSUE THREAD

**Issue by dragosinet** [rkostrzewski/vscode-monitor-file#3]
I think it would be a useful addition an option to scroll to the bottom after reload, so that this plugin can be used as a tail command (get-content <file> -wait from powershell)

**Comment by rkostrzewski** [comment]
Hi, sorry for responding so late. For some weird reason I was not receiving notifications from this repository.

Unfortunately, I'm not planning to work on this extension anymore so I'm gonna close this issue. If you'd like to work on the extension feel free to fork it. Sorry 🙇
