### ISSUE TITLE
doesn' t work if file is deleted and created again

### ISSUE THREAD

**Issue by xgdgsc** [rkostrzewski/vscode-monitor-file#4]
I use google log and want to use vscode to watch the log file. Google log rolls the log everytime it starts. So this plugin doesn' t work in this case. Wondering if it is possible to support this? Thanks.

**Comment by rkostrzewski** [comment]
Hi, sorry for responding so late. For some weird reason I was not receiving notifications from this repository.

Unfortunately, I'm not planning to work on this extension anymore so I'm gonna close this issue. If you'd like to work on the extension feel free to fork it. Sorry 🙇
