### ISSUE TITLE
Getting error to compare file when autosave is on

### ISSUE THREAD

**Issue by HaithamSweilemBM** [rkostrzewski/vscode-monitor-file#5]
When AutoSave is on, vscode gives an error to compare opened file with the disk copy

**Comment by rkostrzewski** [comment]
Hi, sorry for responding so late. For some weird reason I was not receiving notifications from this repository.

Unfortunately, I'm not planning to work on this extension anymore so I'm gonna close this issue. If you'd like to work on the extension feel free to fork it. Sorry 🙇
