### ISSUE TITLE
Does not refresh page

### ISSUE THREAD

**Issue by lepinekong** [rkostrzewski/vscode-monitor-file#6]
I cannot make it work with data exported in realtime by this metatrader indicator that uses:
 file = FileOpen(Symbol() + "-Ticks.csv",
        FILE_WRITE | FILE_READ | FILE_CSV | FILE_SHARE_READ, separator);   

[https://gist.github.com/lepinekong/9a53459b05ac5ed999883eb4a3cb6488](https://gist.github.com/lepinekong/9a53459b05ac5ed999883eb4a3cb6488)

**Comment by rkostrzewski** [comment]
Hi, sorry for responding so late. For some weird reason I was not receiving notifications from this repository.

Unfortunately, I'm not planning to work on this extension anymore so I'm gonna close this issue. If you'd like to work on the extension feel free to fork it. Sorry 🙇
