### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by kanlukasz** [rkostrzewski/vscode-monitor-file#7]
Just not working, no notice, no nothing.
VSCode still refresh file without any prompt

```
Version: 1.38.0-insider
Commit: de320052255d136673fc5eee358f6e2551d6573e
Date: 2019-08-12T07:28:58.576Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Let me know if you need more info
Btw, Is this project dead?

**Comment by rkostrzewski** [comment]
> Just not working, no notice, no nothing.

Looks like it, probably VS Code Extension APIs have changed.

> Btw, Is this project dead?

To be honest I wasn't even aware that people were using the extension and I wasn't receiving notifications from this repository.

Unfortunately, I'm not planning to continue working on this extension as I don't have any need for it. I'll close this issue and mark the repository and extension as archived. Sorry 🙇
